version: '3.4'

services:
  textfixer:
    image: textfixer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
